import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { BlogPost, uniqueCategories } from '@/lib/blog-data';
import { ArrowLeft, Save, Eye, X, Image as ImageIcon, Plus } from 'lucide-react';
import { toast } from 'sonner';

// ImplementationLog
// Date: 2026-01-29
// WHAT: Created BlogEditor component
// WHY: To provide a UI for creating and editing blog posts
// HOW: Using shadcn components and simple state management

interface BlogEditorProps {
    blog?: BlogPost;
    onSave: (blog: BlogPost) => Promise<void>;
    onCancel: () => void;
}

export const BlogEditor: React.FC<BlogEditorProps> = ({ blog, onSave, onCancel }) => {
    // Initial state setup
    // Use blog from props if available as initial state

    // Default empty state
    const defaultBlogState: Omit<BlogPost, 'id'> = {
        title: '',
        slug: '',
        excerpt: '',
        content: '',
        coverImage: '',
        date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
        author: '',
        category: '',
        tags: [],
        readTime: '5 min read',
        published: true
    };

    const [formData, setFormData] = useState<Partial<BlogPost>>(blog || defaultBlogState);
    const [previewMode, setPreviewMode] = useState(false);
    const [tagInput, setTagInput] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);

    // Update form data if blog prop changes
    useEffect(() => {
        if (blog) {
            setFormData(blog);
        }
    }, [blog]);

    // Auto-generate slug from title if not manually set
    const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const title = e.target.value;
        const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');

        setFormData(prev => ({
            ...prev,
            title,
            slug: prev.slug === '' || prev.slug === prev.title?.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '') ? slug : prev.slug
        }));
    };

    // Calculate read time based on content length
    useEffect(() => {
        if (formData.content) {
            const words = formData.content.split(/\s+/).length;
            const minutes = Math.ceil(words / 200);
            setFormData(prev => ({ ...prev, readTime: `${minutes} min read` }));
        }
    }, [formData.content]);

    const handleAddTag = () => {
        if (tagInput.trim() && !formData.tags?.includes(tagInput.trim())) {
            setFormData(prev => ({
                ...prev,
                tags: [...(prev.tags || []), tagInput.trim()]
            }));
            setTagInput('');
        }
    };

    const handleRemoveTag = (tagToRemove: string) => {
        setFormData(prev => ({
            ...prev,
            tags: prev.tags?.filter(tag => tag !== tagToRemove)
        }));
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!formData.title || !formData.slug || !formData.content) {
            toast.error("Please fill in all required fields (Title, Slug, Content)");
            return;
        }

        setIsSubmitting(true);
        try {
            // If editing, use existing ID. If creating, ID will be generated by DB or Service
            // For type safety, we cast, assuming onSave handles the logic
            await onSave(formData as BlogPost);
        } catch (error) {
            console.error("Error saving blog:", error);
            // Toast is handled by parent
        } finally {
            setIsSubmitting(false);
        }
    };

    if (previewMode) {
        return (
            <div className="max-w-4xl mx-auto py-8">
                <Button variant="outline" onClick={() => setPreviewMode(false)} className="mb-6 gap-2">
                    <ArrowLeft className="w-4 h-4" /> Back to Editor
                </Button>

                <div className="bg-white rounded-3xl overflow-hidden shadow-lg border border-gray-100">
                    <div className="h-[400px] relative w-full">
                        {formData.coverImage ? (
                            <img
                                src={formData.coverImage}
                                alt={formData.title}
                                className="w-full h-full object-cover"
                            />
                        ) : (
                            <div className="w-full h-full bg-gray-200 flex items-center justify-center">
                                <span className="text-gray-400">No Cover Image</span>
                            </div>
                        )}
                        <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                        <div className="absolute bottom-0 left-0 p-8 text-white">
                            <div className="flex gap-2 mb-4">
                                <span className="bg-primary px-3 py-1 rounded-full text-xs font-semibold">{formData.category || 'Uncategorized'}</span>
                            </div>
                            <h1 className="text-4xl md:text-5xl font-serif font-bold mb-4">{formData.title}</h1>
                            <div className="flex items-center gap-4 text-sm text-white/80">
                                <span>{formData.date}</span>
                                <span>•</span>
                                <span>{formData.readTime}</span>
                                <span>•</span>
                                <span>By {formData.author || 'Unknown'}</span>
                            </div>
                        </div>
                    </div>

                    <div className="p-8 md:p-12 prose prose-lg max-w-none prose-headings:font-serif prose-a:text-primary">
                        <p className="lead text-xl text-gray-600 mb-8 border-l-4 border-primary pl-4 italic">
                            {formData.excerpt}
                        </p>
                        <div dangerouslySetInnerHTML={{ __html: formData.content || '' }} />
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="max-w-4xl mx-auto">
            <div className="flex items-center justify-between mb-6">
                <Button variant="ghost" onClick={onCancel} className="gap-2">
                    <ArrowLeft className="w-4 h-4" /> Cancel
                </Button>
                <div className="flex gap-2">
                    <Button variant="outline" onClick={() => setPreviewMode(true)} className="gap-2">
                        <Eye className="w-4 h-4" /> Preview
                    </Button>
                    <Button onClick={handleSubmit} disabled={isSubmitting} className="gap-2">
                        <Save className="w-4 h-4" /> {isSubmitting ? 'Saving...' : 'Save Post'}
                    </Button>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="md:col-span-2 space-y-6">
                    <Card>
                        <CardHeader>
                            <CardTitle>Content</CardTitle>
                            <CardDescription>Write your blog post content here.</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div className="space-y-2">
                                <label className="text-sm font-medium">Title *</label>
                                <Input
                                    value={formData.title}
                                    onChange={handleTitleChange}
                                    placeholder="Enter blog title"
                                />
                            </div>

                            <div className="space-y-2">
                                <label className="text-sm font-medium">Slug *</label>
                                <Input
                                    value={formData.slug}
                                    onChange={(e) => setFormData({ ...formData, slug: e.target.value })}
                                    placeholder="url-friendly-slug"
                                />
                            </div>

                            <div className="space-y-2">
                                <label className="text-sm font-medium">Excerpt</label>
                                <Textarea
                                    value={formData.excerpt}
                                    onChange={(e) => setFormData({ ...formData, excerpt: e.target.value })}
                                    placeholder="Short summary for the card view..."
                                    rows={3}
                                />
                            </div>

                            <div className="space-y-2">
                                <label className="text-sm font-medium">Content (HTML supported) *</label>
                                <Textarea
                                    value={formData.content}
                                    onChange={(e) => setFormData({ ...formData, content: e.target.value })}
                                    placeholder="<p>Write your article content here...</p>"
                                    className="min-h-[400px] font-mono text-sm"
                                />
                                <p className="text-xs text-muted-foreground">
                                    Tips: Use &lt;h2&gt; for subtitles, &lt;p&gt; for paragraphs, &lt;blockquote&gt; for quotes.
                                </p>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                <div className="space-y-6">
                    <Card>
                        <CardHeader>
                            <CardTitle>Metadata</CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div className="space-y-2">
                                <label className="text-sm font-medium">
                                    Cover Image <span className="text-xs text-muted-foreground font-normal ml-1">(Recommended: 1920x1080px)</span>
                                </label>
                                <div className="space-y-4">
                                    <div className="flex gap-2">
                                        <div className="relative flex-1">
                                            <Input
                                                type="file"
                                                accept="image/*"
                                                onChange={async (e) => {
                                                    const file = e.target.files?.[0];
                                                    if (!file) return;

                                                    const toastId = toast.loading('Uploading image...');
                                                    try {
                                                        const { uploadBlogImage } = await import('@/services/blog');
                                                        const url = await uploadBlogImage(file);
                                                        setFormData({ ...formData, coverImage: url });
                                                        toast.success('Image uploaded successfully', { id: toastId });
                                                    } catch (error) {
                                                        console.error('Upload failed:', error);
                                                        toast.error('Failed to upload image', { id: toastId });
                                                    }
                                                }}
                                                className="cursor-pointer"
                                            />
                                            <div className="absolute inset-0 flex items-center px-3 pointer-events-none text-muted-foreground text-sm bg-background border rounded-md opacity-0">
                                                Upload Image
                                            </div>
                                        </div>
                                    </div>

                                    <div className="relative">
                                        <div className="absolute inset-0 flex items-center">
                                            <span className="w-full border-t" />
                                        </div>
                                        <div className="relative flex justify-center text-xs uppercase">
                                            <span className="bg-background px-2 text-muted-foreground">Or use URL</span>
                                        </div>
                                    </div>

                                    <Input
                                        value={formData.coverImage}
                                        onChange={(e) => setFormData({ ...formData, coverImage: e.target.value })}
                                        placeholder="https://..."
                                    />
                                </div>

                                {formData.coverImage && (
                                    <div className="relative aspect-video rounded-md overflow-hidden bg-gray-100 border mt-2 group">
                                        <img src={formData.coverImage} alt="Preview" className="w-full h-full object-cover" />
                                        <Button
                                            variant="destructive"
                                            size="icon"
                                            className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity"
                                            onClick={() => setFormData({ ...formData, coverImage: '' })}
                                        >
                                            <X className="w-4 h-4" />
                                        </Button>
                                    </div>
                                )}
                            </div>

                            <div className="space-y-2">
                                <label className="text-sm font-medium">Category</label>
                                <select
                                    className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                                    value={formData.category}
                                    onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                                >
                                    <option value="">Select Category</option>
                                    {uniqueCategories.map(cat => (
                                        <option key={cat} value={cat}>{cat}</option>
                                    ))}
                                    <option value="News">News</option>
                                    <option value="Updates">Updates</option>
                                </select>
                            </div>

                            <div className="space-y-2">
                                <label className="text-sm font-medium">Author</label>
                                <Input
                                    value={formData.author}
                                    onChange={(e) => setFormData({ ...formData, author: e.target.value })}
                                    placeholder="Author name"
                                />
                            </div>



                            <div className="space-y-2">
                                <label className="text-sm font-medium">Tags</label>
                                <div className="flex gap-2">
                                    <Input
                                        value={tagInput}
                                        onChange={(e) => setTagInput(e.target.value)}
                                        onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), handleAddTag())}
                                        placeholder="Add tag..."
                                    />
                                    <Button type="button" size="icon" variant="secondary" onClick={handleAddTag}>
                                        <Plus className="w-4 h-4" />
                                    </Button>
                                </div>
                                <div className="flex flex-wrap gap-2 mt-2">
                                    {formData.tags?.map(tag => (
                                        <span key={tag} className="bg-secondary text-secondary-foreground px-2 py-1 rounded-md text-xs flex items-center gap-1">
                                            {tag}
                                            <button onClick={() => handleRemoveTag(tag)} className="hover:text-destructive">
                                                <X className="w-3 h-3" />
                                            </button>
                                        </span>
                                    ))}
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>
    );
};
